
CREATE TABLE students(id serial PRIMARY KEY ,name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL , createdAt DATE NOT NULL DEFAULT CURRENT_DATE , updatedAt DATE NOT NULL DEFAULT CURRENT_DATE);
